name: CI

on: [push]

jobs:
  MyNoteApp:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]  
    
    env:
      NODE_ENV: "ci"    
      
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    # 1: setup node
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12

    # 2: Checkout repository in the CWD
    - name: Checkout repository
      uses: actions/checkout@v2

    # 3: install NPM dependencies
    - name: Install dependencies
      run: npm install
    
    - name: Build
      run: npm run build
    
    
     #4: run test command
    - name: Run test command
      run: npm run test    


    #5 Deploy step  
    - name: Deploy to Heroku
      run: |
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

